name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Show free disk space before build
        run: |
          echo "Free disk space before build:"
          df -h

      - name: Show Gradle and Java version
        run: |
          echo "Gradle version:"
          ./gradlew --version
          echo "Java version:"
          java -version

      - name: Build WASM/JS distribution
        run: |
          echo "Running WASM/JS build..."
          ./gradlew :composeApp:wasmJsBrowserDevelopmentRun || { echo "Error during WASM/JS build"; cat composeApp/build/reports/* || true; exit 1; }
          echo "WASM/JS build finished."

      - name: List generated files
        run: |
          echo "Generated files in build/wasm/packages/composeApp/kotlin/"
          ls -l build/wasm/packages/composeApp/kotlin/

      - name: List files in docs
        run: |
          echo "Files in docs/ before copying"
          ls -l docs/

      - name: Copy build output to docs
        run: |
          set -e
          mkdir -p docs
          cp -r build/wasm/packages/composeApp/kotlin/* docs/ || { echo "ERROR: Could not copy generated files. Check the path and the build."; exit 1; }
          echo "Files in docs/ after copying:"
          ls -l docs/
          echo "Permissions and owner of files in docs/:"
          ls -l docs/

      - name: Show content of index.html in docs
        run: |
          echo "Content of docs/index.html:"
          cat docs/index.html

      - name: Show repository status before commit
        run: |
          git status

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git commit -m "Deploy latest build to docs for GitHub Pages" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} main
          echo "Hash of the latest commit:"
          git rev-parse HEAD
